version: "2"
services:
  backend:
    image: lucky/lucky_box/cms_server:latest
    ports:
      - 8003:8003
    networks:
      net:
        aliases:
          - backend
    restart: always
    tty: true
    volumes:
      - "./deploy/start.log:/app/start.log"
      - "./deploy/panic.log:/app/panic.log"
      - "./deploy/logs:/app/storage/logs"
      - "./cms/configs:/app/configs"

  frontend:
    image: lucky/lucky_box/cms_frontend:latest
    ports:
      - 8081:8081
    networks:
      net:
        aliases:
          - frontend
    restart: always
    tty: true
    volumes:
      - "./view/dist_prod:/app/dist"

networks:
  net:


volumes:
  redisData: {}
