version: "2"
services:
  cms_server:
    image: registry.cn-hangzhou.aliyuncs.com/jixiangshang/cms_server:latest
    ports:
      - 8003:8003
    networks:
      net:
        aliases:
          - cms_server
    restart: always
    tty: true
    volumes:
      - "./start.log:/app/start.log"
      - "./panic.log:/app/panic.log"
      - "./logs:/app/storage/logs"
      - "./configs:/app/configs"

networks:
  net:


volumes:
  redisData: {}
