Server:
  ServerName: cms
  Version: v2
  # release, debug, migrate
  RunMode: debug
  HttpPort: 8003
  ReadTimeout: 60
  WriteTimeout: 60
  TimeZone: Asia/Shanghai
  Language: zh
  WhiteList:
    - 127.0.0.1
    - localhost

App:
  DefaultPageSize: 10
  MaxPageSize: 100
  DefaultContextTimeout: 60

Tel:
  AreaCode: 86
  FullPhoneNumLength: 11

JWT:
  Secret: Jixianshang
  Issuer: Jixianshang-cms
  Expire: 24

SecretKey:
  AesKey: "!2023chaoshe"
  AesVi: "!2023chaoshe"

Logger:
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log

WeChat:
  WebHook: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=bbd2cb35-b214-44a2-a7cb-8a9e6679697a

Database:
  CenterDB: "root:BfoofPx9gPvpd2isRHKH@tcp(118.89.55.18:13306)/blind_box?charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai&multiStatements=True"
#  CenterDB: "root:123456@tcp(192.168.0.93:3306)/blind_box?charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai&multiStatements=True"
  CMSDB: "root:123456@tcp(192.168.0.93:3306)/cms_data?charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai&multiStatements=True"
  # 数据库连接池大小
  Pool: 5
  # 同时打开的连接数
  ConnMaxLifetime: 100

Redis:
  Host: "192.168.0.93:6379"
  Password: 123456
  CMSDB: 6

